version: "2"
services:
  revproxy:
    build:
      context: "."
      dockerfile: "Dockerfile.nginx"
    links:
      - "web"
    ports:
      - "80:80"
  web:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment: 
      - FLASK_APP=app.py
    volumes:
      - "./src:/src"
    command: "flask run --host 0.0.0.0" 